services:
  - type: web
    name: icp-crm
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn crm.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
